name: CI
on:
  push:
    branches: 
      - main
env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  REGISTRY_HOSTNAME: asia-southeast1-docker.pkg.dev
  PROJECT_NAME: asc-fintech-dev
  REPOSITORY_NAME: dev-apollotech-co
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "gitrepository=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - name: Check-out the code from repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Authorize Docker Registry
        run: gcloud auth configure-docker "$REGISTRY_HOSTNAME"
      - name: Build docker image
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_SHA" .
        env:
          GIT_REPOSITORY: ${{ steps.setup.outputs.gitrepository }}
      - name: Push docker image
        run: |
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_SHA"
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":latest
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":latest
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_RUN_NUMBER"
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$REPOSITORY_NAME"/"$GIT_REPOSITORY":"$GITHUB_RUN_NUMBER"
        env:
          GIT_REPOSITORY: ${{ steps.setup.outputs.gitrepository }}
